version: '3'
services:
  db:
    container_name: db_tour
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_tour:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tour
      MYSQL_ROOT_PASSWORD: root
    logging:
      driver: "json-file"
      options:
        max-size: 500m

volumes:
  db_tour: